// <auto-generated />
using System;
using BuiManhCuong126.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BuiManhCuong126.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20241018011500_Create_Table_Employee")]
    partial class Create_Table_Employee
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.10");

            modelBuilder.Entity("BuiManhCuong126.Models.Employee", b =>
                {
                    b.Property<string>("Hoten")
                        .HasColumnType("TEXT");

                    b.Property<int>("MaSinhVien")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Ngaysinh")
                        .HasColumnType("TEXT");

                    b.HasKey("Hoten");

                    b.ToTable("Employee");
                });
#pragma warning restore 612, 618
        }
    }
}
